import { z } from "zod";

export const propertySchema = z.object({
    size_unit: z.string().min(1, "Name is required"),
    size: z.string().optional(),
    title: z.string().optional(),
    description: z.string().min(1, "Email is required").email("Invalid email"),
    type: z.string().optional(),
    category: z.string().optional(),
    location: z.string().optional(),
    price: z.string().optional(),
    built_up_area: z.string().optional(),
    carpet_area: z.string().optional(),
    unit_area_type: z.string().optional(),
    plot_front_area: z.string().optional(),
    plot_depth_area: z.string().optional(),
    plot_dimension_unit: z.string().optional(),
    is_corner_plot: z.string().optional(),
    bedrooms: z.string().optional(),
    bathrooms: z.string().optional(),
    balconies: z.string().optional(),
    washrooms: z.string().optional(),
    cabins: z.string().optional(),
    conference_rooms: z.string().optional(),
    floor_number: z.string().optional(),
    total_floors: z.string().optional(),
    facing: z.string().optional(),
    overlooking: z.string().optional(),
    property_age: z.string().optional(),
    transaction_type: z.string().optional(),
    gated_community: z.string().optional(),
    water_source: z.string().optional(),
    power_backup: z.string().optional(),
    furnishing: z.string().optional(),
    features: z.string().optional(),
    amenities: z.string().optional(),
    images: z.string().optional(),
    status: z.string().optional(),
});

export type PropertyFormDataSchema = z.infer<typeof propertySchema>;
