import { z } from 'zod';

export const propertySchema = z.object({
    title: z.string().min(1, 'Title is required'),
    description: z.string().optional(),
    type: z.enum(['residential', 'commercial']),
    category: z.enum(['plot', 'flat', 'showroom', 'office', 'villa', 'land']),
    location: z.string().min(1, 'Location is required'),
    price: z.number().min(1, 'Price must be greater than 0'),
    size: z.number().optional(),
    size_unit: z.string().min(1, 'Unit is required'),
    bedrooms: z.number().optional(),
    bathrooms: z.number().optional(),
    washrooms: z.number().optional(),
    balconies: z.number().optional(),
    cabins: z.number().optional(),
    conference_rooms: z.number().optional(),
    floor_number: z.number().optional(),
    total_floors: z.number().optional(),
    owner_name: z.string().optional(),
    owner_contact: z.string().optional(),
    owner_notes: z.string().optional(),
    images: z.array(z.string()).optional(),
    property_code: z.string().optional(),
    rera_status: z.enum(['Available', 'Not Available', 'Applied']).optional(),
    rera_id: z.string().optional(),
    status: z.enum(['Available', 'Pending', 'Sold', 'Rented']).optional(),
    built_up_area: z.number().optional(),
    carpet_area: z.number().optional(),
    unit_area_type: z.enum(['sqft', 'sqm', 'acre', 'marla', 'kanal', 'bigha', 'sqyd', 'hectare']).optional(),
    facing: z.enum(['North', 'South', 'East', 'West', 'North-East', 'North-West', 'South-East', 'South-West']).optional(),
    overlooking: z.array(z.string()).optional(),
    property_age: z.enum(['New', '1-5 years', '5-10 years', '10+ years']).optional(),
    transaction_type: z.enum(['New', 'Resale']).optional(),
    ownership_type: z.enum(['Freehold', 'Leasehold', 'Co-operative Society', 'Power of Attorney']).optional(),
    gated_community: z.boolean().optional(),
    parking_count: z.number().optional(),
    water_source: z.array(z.string()).optional(),
    power_backup: z.enum(['None', 'Partial', 'Full']).optional(),
    flooring_type: z.string().optional(),
    furnishing: z.enum(['Unfurnished', 'Semi-Furnished', 'Furnished']).optional(),
    amenities: z.array(z.string()).optional(),
    owner: z.string().optional(),
    agency: z.string().optional(),
    created_at: z.date().optional(),
    updated_at: z.date().optional(),
});

export type PropertyFormData = z.infer<typeof propertySchema>;
